In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from latex_conf import build_latex_confusion_matrix

In [2]:
df_phish = pd.read_csv("result_custom_.txt", sep="\t")
df_phish["is_phish"] = 1
df_benign = pd.read_csv("result_custom_benign.txt", sep="\t")
df_benign["is_phish"] = 0

df = df_phish.append(df_benign, ignore_index=True)

df_phish["phish_category"] = np.where(df_phish['true_brand'] == df_phish['pred_brand'], 1, 0)
df_rec = df_phish.append(df_benign, ignore_index=True)

/tmp/ipykernel_395900/3160026256.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df_phish.append(df_benign, ignore_index=True)
/tmp/ipykernel_395900/3160026256.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_rec = df_phish.append(df_benign, ignore_index=True)

In [3]:
df_phish

,folder,true_brand,phish_category,pred_brand,runtime_element_recognition,runtime_siamese,is_phish
0,Instagram+257,Instagram,0,Dropbox,0.126377,0.117751,1
1,WeTransfer+80,WeTransfer,0,HSBC Bank,0.143455,0.042208,1
2,Blockchain+6,Blockchain,0,Chase Personal Banking,0.140124,0.202224,1
3,WhatsApp+366,WhatsApp,0,SOCIETE FRANCAISE DU RADIOTELEPHONE,0.159884,0.169148,1
4,Adobe+270,Adobe,0,Chase Personal Banking,0.146677,0.153191,1
...,...,...,...,...,...,...,...
17451,Etisalat+263,Etisalat,0,PostFinance,0.145771,0.040646,1
17452,American Express+137,American Express,0,National Bank of Canada,0.144105,0.040870,1
17453,Deutsche Telekom+400,Deutsche Telekom,0,NatWest Personal Banking,0.141236,0.046362,1
17454,Navy Federal Credit Union+78,Navy Federal Credit Union,0,Neteller,0.154184,0.237481,1
17455,Steam+142,Steam,0,Netflix,0.155959,0.049558,1

In [4]:
df_benign

,folder,true_brand,phish_category,pred_brand,runtime_element_recognition,runtime_siamese,is_phish
0,seyfarth.com,seyfarth.com,1,Deutsche Telekom,0.119327,0.041735,0
1,nencinisport.it,nencinisport.it,1,Bet365,0.122398,0.033599,0
2,cupraofficial.de,cupraofficial.de,1,PostFinance,0.126397,0.034548,0
3,www.mountainsteals.com,www.mountainsteals.com,1,1&1 Ionos,0.114496,0.031224,0
4,4sysops.com,4sysops.com,1,Societe Generale,0.119186,0.104092,0
...,...,...,...,...,...,...,...
13460,paysync-prod-fa.azurewebsites.net,paysync-prod-fa.azurewebsites.net,1,Luno,0.117037,0.062352,0
13461,replicate.com,replicate.com,1,Bank of The Bahamas Limited,0.115745,0.028860,0
13462,pod-000-1401-14.backblaze.com,pod-000-1401-14.backblaze.com,1,DocuSign,0.118368,0.029757,0
13463,cekreport.com,cekreport.com,1,Microsoft,0.127611,0.033726,0
13464,coinflation.com,coinflation.com,1,Luno,0.120293,0.096189,0

In [5]:
df

,folder,true_brand,phish_category,pred_brand,runtime_element_recognition,runtime_siamese,is_phish
0,Instagram+257,Instagram,1,Dropbox,0.126377,0.117751,1
1,WeTransfer+80,WeTransfer,1,HSBC Bank,0.143455,0.042208,1
2,Blockchain+6,Blockchain,1,Chase Personal Banking,0.140124,0.202224,1
3,WhatsApp+366,WhatsApp,1,SOCIETE FRANCAISE DU RADIOTELEPHONE,0.159884,0.169148,1
4,Adobe+270,Adobe,1,Chase Personal Banking,0.146677,0.153191,1
...,...,...,...,...,...,...,...
30916,paysync-prod-fa.azurewebsites.net,paysync-prod-fa.azurewebsites.net,1,Luno,0.117037,0.062352,0
30917,replicate.com,replicate.com,1,Bank of The Bahamas Limited,0.115745,0.028860,0
30918,pod-000-1401-14.backblaze.com,pod-000-1401-14.backblaze.com,1,DocuSign,0.118368,0.029757,0
30919,cekreport.com,cekreport.com,1,Microsoft,0.127611,0.033726,0
30920,coinflation.com,coinflation.com,1,Luno,0.120293,0.096189,0

In [6]:
confusion_matrix = pd.crosstab(df['is_phish'], df['phish_category'], rownames=['Actual'], colnames=['Predicted'], margins=True)
confusion_matrix_rec = pd.crosstab(df_rec['is_phish'], df_rec['phish_category'], rownames=['Actual'], colnames=['Predicted'], margins=True)

In [7]:
confusion_matrix

Predicted     0      1    All
Actual
0          2521  10944  13465
1          2624  14832  17456
All        5145  25776  30921

In [8]:
confusion_matrix_rec

Predicted      0      1    All
Actual
0           2521  10944  13465
1          16327   1129  17456
All        18848  12073  30921

In [9]:
tp, tp_rec = confusion_matrix[1][1], confusion_matrix_rec[1][1]
fp, fp_rec = confusion_matrix[1][0], confusion_matrix_rec[1][0]
fn, fn_rec = confusion_matrix[0][1], confusion_matrix_rec[0][1]
ppv = tp / (tp + fp)
ppv_rec = tp_rec / (tp_rec + fp_rec)
print(f"Precision: {ppv}, Precision brand: {ppv_rec}")

Precision: 0.5754189944134078, Precision brand: 0.09351445373974986

In [10]:
tpr = tp / (tp + fn)
tpr_rec = tp_rec / (tp_rec + fn_rec)
print(f"Sensitivity: {tpr}, Sensitivity brand: {tpr_rec}")

Sensitivity: 0.84967919340055, Sensitivity brand: 0.0646769019248396

In [11]:
print(build_latex_confusion_matrix(confusion_matrix))

\def \cTP {14832}
\def \cFP {10944}
\def \cTN {2521}
\def \cFN {2624}
\def \ctiP {17456}
\def \ctiN {13465}
\def \ctpP {25776}
\def \cFpN {5145}
\def \ctotal {30921}
\def \cPPV {57.5\%}
\def \cTPR {85.0\%}
\def \cACC {56.1\%}

In [12]:
print(build_latex_confusion_matrix(confusion_matrix_rec))

\def \cTP {1129}
\def \cFP {10944}
\def \cTN {2521}
\def \cFN {16327}
\def \ctiP {17456}
\def \ctiN {13465}
\def \ctpP {12073}
\def \cFpN {18848}
\def \ctotal {30921}
\def \cPPV {9.4\%}
\def \cTPR {6.5\%}
\def \cACC {11.8\%}